sudo: required
services:
  - docker

before_install:
  - docker build -t appcicd/react-docker -f Dockerfile.dev .

script:
  - docker run appcicd/react-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-us-west-1-524167333514"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"